### ISSUE TITLE
Can you add smtp option ? 

### ISSUE THREAD

**Issue by Prostu2** [AlexusBlack/alexusMailer-2#1]
Thanks

**Comment by AlexusBlack** [comment]
@Prostu2 hey, while it is possible from php side it would require a lot of work. I stopped development of the script and open sourced it due to lack of time, need and interest.
If you want to use it with some specific smtp server you can reconfigure your server sendmail to send via smtp.

**Comment by 0r00t** [comment]
that would be lovely because this is one of the best tool so far till today 2022
